using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace SpaceShooter
{
    public class EnitySpawner : MonoBehaviour
    {
        public enum SpawnMode
        {
            Start,
            Loop
        }


        [SerializeField] private GameObject[] m_EntityPrefabs;
        [SerializeField] private CircleArea m_Area;
        [SerializeField] private SpawnMode m_SpawnMode;
        [SerializeField] private int m_NumSpawn;//кол-во спавнов
        [SerializeField] private float m_RespawnTime;
        

        private float m_Timer;


        


        private void Start()
        {
            if(m_SpawnMode == SpawnMode.Start)
            {
                SpawnEntities();
            }
            m_Timer = m_RespawnTime;
        }



        private void Update()
        {
            if (m_Timer > 0)
                m_Timer -= Time.deltaTime;

            if(m_SpawnMode == SpawnMode.Loop && m_Timer < 0)
            {
                SpawnEntities();
                
                m_Timer = m_RespawnTime;
            }
        }



        private void SpawnEntities()
        {
            for(int i = 0; i < m_NumSpawn; i++)
            {
                int index = Random.Range(0, m_EntityPrefabs.Length);
                GameObject e = Instantiate(m_EntityPrefabs[index].gameObject);
                

                e.transform.position = m_Area.GetRandomInsideZone();
            }
        }




        




        





    }
}
